M48
; DRILL file {KiCad 8.0.1-rc1} date 2024-11-12T19:52:44-0600
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-12T19:52:44-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1-rc1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0413
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0512
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1285
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1300
%
G90
G05
T1
X3.825Y-5.0718
T2
X3.825Y-4.7785
T3
X2.6Y-1.35
X2.6Y-6.65
X4.0Y-1.35
X4.0Y-6.65
T4
X2.805Y-6.7115
X2.9639Y-6.7115
X3.13Y-6.7115
X3.2889Y-6.7115
M30
