M48
; DRILL file {KiCad 9.0.3} date 2025-10-21T13:29:57-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-10-21T13:29:57-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0413
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0512
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1285
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1300
%
G90
G05
T1
X6.175Y-3.2933
T2
X6.175Y-3.5867
T3
X4.65Y-1.05
X4.65Y-5.25
X6.35Y-1.05
X6.35Y-5.25
T4
X4.8456Y-4.944
X5.0044Y-4.944
X5.9956Y-4.944
X6.1544Y-4.944
M30
